use_frameworks!

platform :ios, '8.0'

target 'YJNetSpeedMonitor_Example' do
  pod 'YJNetSpeedMonitor', :path => '../'

  target 'YJNetSpeedMonitor_Tests' do
    inherit! :search_paths

    
  end
end
